services:
  ahsa:
    image: node:18-alpine
    container_name: ahsa-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: "sh -c 'pnpm install && pnpm run dev'"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: ahsa-db
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ahsa
      POSTGRES_PASSWORD: ahsa
      POSTGRES_DB: ahsa_dev
    ports:
      - "5436:5432"

volumes:
  db-data:
